from vkbottle import BaseStateGroup


class BotStates(BaseStateGroup):
    REG_GET_FULL_NAME = 1
    REG_GET_GROUP = 2
    REG_GET_PHONE = 3
    REG_GET_BIRTH_DATE = 4
    REG_GET_INST = 5
    GET_OTHER_PROFILE = 6
    SET_STRIKE = 7
    CANCEL_STRIKE = 8
    RATE_COMP = 9
    RATE_COMP_NEXT = 10
    MARK_ABSENT = 11
    KICK_AC = 12
    GET_CALENDAR = 13
    DEADLINE_GET_NAME = 14
    DEADLINE_GET_TIME = 15
    DEADLINE_ACCEPT = 16
    HW_CHOOSE = 17
    HW_GET_NAME = 18
    HW_PASS = 19
    HW_GET_FILE = 20
    HW_CHOOSE_ADM = 21
    TOP_GET_TAG = 22
    TOP_GET_ORDER_BY = 23
